/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedMeusPresentesRouteImport } from './routes/_authenticated/meus-presentes'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as CasamentoSlugRouteImport } from './routes/casamento.$slug'
import { Route as AuthenticatedConviteTokenRouteImport } from './routes/_authenticated/convite.$token'
import { Route as CasamentoSlugIndexRouteImport } from './routes/casamento.$slug.index'
import { Route as CasamentoSlugAvisosRouteImport } from './routes/casamento.$slug.avisos'
import { Route as CasamentoSlugConfirmarRouteImport } from './routes/casamento.$slug.confirmar'
import { Route as CasamentoSlugFestaRouteImport } from './routes/casamento.$slug.festa'
import { Route as CasamentoSlugFornecedoresRouteImport } from './routes/casamento.$slug.fornecedores'
import { Route as CasamentoSlugGaleriaRouteImport } from './routes/casamento.$slug.galeria'
import { Route as CasamentoSlugHistoriaRouteImport } from './routes/casamento.$slug.historia'
import { Route as CasamentoSlugPadrinhosRouteImport } from './routes/casamento.$slug.padrinhos'
import { Route as CasamentoSlugPresentesRouteImport } from './routes/casamento.$slug.presentes'
import { Route as CasamentoSlugRecadosRouteImport } from './routes/casamento.$slug.recados'
import { Route as CasamentoSlugPresenteGiftIdRouteImport } from './routes/casamento.$slug.presente.$giftId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeusPresentesRoute =
  AuthenticatedMeusPresentesRouteImport.update({
    id: '/meus-presentes',
    path: '/meus-presentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CasamentoSlugRoute = CasamentoSlugRouteImport.update({
  id: '/casamento/$slug',
  path: '/casamento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConviteTokenRoute =
  AuthenticatedConviteTokenRouteImport.update({
    id: '/convite/$token',
    path: '/convite/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CasamentoSlugIndexRoute = CasamentoSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasamentoSlugRoute,
} as any)
const CasamentoSlugAvisosRoute = CasamentoSlugAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => CasamentoSlugRoute,
} as any)
const CasamentoSlugConfirmarRoute = CasamentoSlugConfirmarRouteImport.update({
  id: '/confirmar',
  path: '/confirmar',
  getParentRoute: () => CasamentoSlugRoute,
} as any)
const CasamentoSlugFestaRoute = CasamentoSlugFestaRouteImport.update({
  id: '/festa',
  path: '/festa',
  getParentRoute: () => CasamentoSlugRoute,
} as any)
const CasamentoSlugFornecedoresRoute =
  CasamentoSlugFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => CasamentoSlugRoute,
  } as any)
const CasamentoSlugGaleriaRoute = CasamentoSlugGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => CasamentoSlugRoute,
} as any)
const CasamentoSlugHistoriaRoute = CasamentoSlugHistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => CasamentoSlugRoute,
} as any)
const CasamentoSlugPadrinhosRoute = CasamentoSlugPadrinhosRouteImport.update({
  id: '/padrinhos',
  path: '/padrinhos',
  getParentRoute: () => CasamentoSlugRoute,
} as any)
const CasamentoSlugPresentesRoute = CasamentoSlugPresentesRouteImport.update({
  id: '/presentes',
  path: '/presentes',
  getParentRoute: () => CasamentoSlugRoute,
} as any)
const CasamentoSlugRecadosRoute = CasamentoSlugRecadosRouteImport.update({
  id: '/recados',
  path: '/recados',
  getParentRoute: () => CasamentoSlugRoute,
} as any)
const CasamentoSlugPresenteGiftIdRoute =
  CasamentoSlugPresenteGiftIdRouteImport.update({
    id: '/presente/$giftId',
    path: '/presente/$giftId',
    getParentRoute: () => CasamentoSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meus-presentes': typeof AuthenticatedMeusPresentesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/casamento/$slug': typeof CasamentoSlugRouteWithChildren
  '/convite/$token': typeof AuthenticatedConviteTokenRoute
  '/casamento/$slug/avisos': typeof CasamentoSlugAvisosRoute
  '/casamento/$slug/confirmar': typeof CasamentoSlugConfirmarRoute
  '/casamento/$slug/festa': typeof CasamentoSlugFestaRoute
  '/casamento/$slug/fornecedores': typeof CasamentoSlugFornecedoresRoute
  '/casamento/$slug/galeria': typeof CasamentoSlugGaleriaRoute
  '/casamento/$slug/historia': typeof CasamentoSlugHistoriaRoute
  '/casamento/$slug/padrinhos': typeof CasamentoSlugPadrinhosRoute
  '/casamento/$slug/presentes': typeof CasamentoSlugPresentesRoute
  '/casamento/$slug/recados': typeof CasamentoSlugRecadosRoute
  '/casamento/$slug/': typeof CasamentoSlugIndexRoute
  '/casamento/$slug/presente/$giftId': typeof CasamentoSlugPresenteGiftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meus-presentes': typeof AuthenticatedMeusPresentesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/convite/$token': typeof AuthenticatedConviteTokenRoute
  '/casamento/$slug/avisos': typeof CasamentoSlugAvisosRoute
  '/casamento/$slug/confirmar': typeof CasamentoSlugConfirmarRoute
  '/casamento/$slug/festa': typeof CasamentoSlugFestaRoute
  '/casamento/$slug/fornecedores': typeof CasamentoSlugFornecedoresRoute
  '/casamento/$slug/galeria': typeof CasamentoSlugGaleriaRoute
  '/casamento/$slug/historia': typeof CasamentoSlugHistoriaRoute
  '/casamento/$slug/padrinhos': typeof CasamentoSlugPadrinhosRoute
  '/casamento/$slug/presentes': typeof CasamentoSlugPresentesRoute
  '/casamento/$slug/recados': typeof CasamentoSlugRecadosRoute
  '/casamento/$slug': typeof CasamentoSlugIndexRoute
  '/casamento/$slug/presente/$giftId': typeof CasamentoSlugPresenteGiftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/meus-presentes': typeof AuthenticatedMeusPresentesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/casamento/$slug': typeof CasamentoSlugRouteWithChildren
  '/_authenticated/convite/$token': typeof AuthenticatedConviteTokenRoute
  '/casamento/$slug/avisos': typeof CasamentoSlugAvisosRoute
  '/casamento/$slug/confirmar': typeof CasamentoSlugConfirmarRoute
  '/casamento/$slug/festa': typeof CasamentoSlugFestaRoute
  '/casamento/$slug/fornecedores': typeof CasamentoSlugFornecedoresRoute
  '/casamento/$slug/galeria': typeof CasamentoSlugGaleriaRoute
  '/casamento/$slug/historia': typeof CasamentoSlugHistoriaRoute
  '/casamento/$slug/padrinhos': typeof CasamentoSlugPadrinhosRoute
  '/casamento/$slug/presentes': typeof CasamentoSlugPresentesRoute
  '/casamento/$slug/recados': typeof CasamentoSlugRecadosRoute
  '/casamento/$slug/': typeof CasamentoSlugIndexRoute
  '/casamento/$slug/presente/$giftId': typeof CasamentoSlugPresenteGiftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/meus-presentes'
    | '/painel'
    | '/super-admin'
    | '/casamento/$slug'
    | '/convite/$token'
    | '/casamento/$slug/avisos'
    | '/casamento/$slug/confirmar'
    | '/casamento/$slug/festa'
    | '/casamento/$slug/fornecedores'
    | '/casamento/$slug/galeria'
    | '/casamento/$slug/historia'
    | '/casamento/$slug/padrinhos'
    | '/casamento/$slug/presentes'
    | '/casamento/$slug/recados'
    | '/casamento/$slug/'
    | '/casamento/$slug/presente/$giftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/meus-presentes'
    | '/painel'
    | '/super-admin'
    | '/convite/$token'
    | '/casamento/$slug/avisos'
    | '/casamento/$slug/confirmar'
    | '/casamento/$slug/festa'
    | '/casamento/$slug/fornecedores'
    | '/casamento/$slug/galeria'
    | '/casamento/$slug/historia'
    | '/casamento/$slug/padrinhos'
    | '/casamento/$slug/presentes'
    | '/casamento/$slug/recados'
    | '/casamento/$slug'
    | '/casamento/$slug/presente/$giftId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/meus-presentes'
    | '/_authenticated/painel'
    | '/_authenticated/super-admin'
    | '/casamento/$slug'
    | '/_authenticated/convite/$token'
    | '/casamento/$slug/avisos'
    | '/casamento/$slug/confirmar'
    | '/casamento/$slug/festa'
    | '/casamento/$slug/fornecedores'
    | '/casamento/$slug/galeria'
    | '/casamento/$slug/historia'
    | '/casamento/$slug/padrinhos'
    | '/casamento/$slug/presentes'
    | '/casamento/$slug/recados'
    | '/casamento/$slug/'
    | '/casamento/$slug/presente/$giftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CasamentoSlugRoute: typeof CasamentoSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meus-presentes': {
      id: '/_authenticated/meus-presentes'
      path: '/meus-presentes'
      fullPath: '/meus-presentes'
      preLoaderRoute: typeof AuthenticatedMeusPresentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/casamento/$slug': {
      id: '/casamento/$slug'
      path: '/casamento/$slug'
      fullPath: '/casamento/$slug'
      preLoaderRoute: typeof CasamentoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/convite/$token': {
      id: '/_authenticated/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof AuthenticatedConviteTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/casamento/$slug/': {
      id: '/casamento/$slug/'
      path: '/'
      fullPath: '/casamento/$slug/'
      preLoaderRoute: typeof CasamentoSlugIndexRouteImport
      parentRoute: typeof CasamentoSlugRoute
    }
    '/casamento/$slug/avisos': {
      id: '/casamento/$slug/avisos'
      path: '/avisos'
      fullPath: '/casamento/$slug/avisos'
      preLoaderRoute: typeof CasamentoSlugAvisosRouteImport
      parentRoute: typeof CasamentoSlugRoute
    }
    '/casamento/$slug/confirmar': {
      id: '/casamento/$slug/confirmar'
      path: '/confirmar'
      fullPath: '/casamento/$slug/confirmar'
      preLoaderRoute: typeof CasamentoSlugConfirmarRouteImport
      parentRoute: typeof CasamentoSlugRoute
    }
    '/casamento/$slug/festa': {
      id: '/casamento/$slug/festa'
      path: '/festa'
      fullPath: '/casamento/$slug/festa'
      preLoaderRoute: typeof CasamentoSlugFestaRouteImport
      parentRoute: typeof CasamentoSlugRoute
    }
    '/casamento/$slug/fornecedores': {
      id: '/casamento/$slug/fornecedores'
      path: '/fornecedores'
      fullPath: '/casamento/$slug/fornecedores'
      preLoaderRoute: typeof CasamentoSlugFornecedoresRouteImport
      parentRoute: typeof CasamentoSlugRoute
    }
    '/casamento/$slug/galeria': {
      id: '/casamento/$slug/galeria'
      path: '/galeria'
      fullPath: '/casamento/$slug/galeria'
      preLoaderRoute: typeof CasamentoSlugGaleriaRouteImport
      parentRoute: typeof CasamentoSlugRoute
    }
    '/casamento/$slug/historia': {
      id: '/casamento/$slug/historia'
      path: '/historia'
      fullPath: '/casamento/$slug/historia'
      preLoaderRoute: typeof CasamentoSlugHistoriaRouteImport
      parentRoute: typeof CasamentoSlugRoute
    }
    '/casamento/$slug/padrinhos': {
      id: '/casamento/$slug/padrinhos'
      path: '/padrinhos'
      fullPath: '/casamento/$slug/padrinhos'
      preLoaderRoute: typeof CasamentoSlugPadrinhosRouteImport
      parentRoute: typeof CasamentoSlugRoute
    }
    '/casamento/$slug/presentes': {
      id: '/casamento/$slug/presentes'
      path: '/presentes'
      fullPath: '/casamento/$slug/presentes'
      preLoaderRoute: typeof CasamentoSlugPresentesRouteImport
      parentRoute: typeof CasamentoSlugRoute
    }
    '/casamento/$slug/recados': {
      id: '/casamento/$slug/recados'
      path: '/recados'
      fullPath: '/casamento/$slug/recados'
      preLoaderRoute: typeof CasamentoSlugRecadosRouteImport
      parentRoute: typeof CasamentoSlugRoute
    }
    '/casamento/$slug/presente/$giftId': {
      id: '/casamento/$slug/presente/$giftId'
      path: '/presente/$giftId'
      fullPath: '/casamento/$slug/presente/$giftId'
      preLoaderRoute: typeof CasamentoSlugPresenteGiftIdRouteImport
      parentRoute: typeof CasamentoSlugRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMeusPresentesRoute: typeof AuthenticatedMeusPresentesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedConviteTokenRoute: typeof AuthenticatedConviteTokenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMeusPresentesRoute: AuthenticatedMeusPresentesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedConviteTokenRoute: AuthenticatedConviteTokenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CasamentoSlugRouteChildren {
  CasamentoSlugAvisosRoute: typeof CasamentoSlugAvisosRoute
  CasamentoSlugConfirmarRoute: typeof CasamentoSlugConfirmarRoute
  CasamentoSlugFestaRoute: typeof CasamentoSlugFestaRoute
  CasamentoSlugFornecedoresRoute: typeof CasamentoSlugFornecedoresRoute
  CasamentoSlugGaleriaRoute: typeof CasamentoSlugGaleriaRoute
  CasamentoSlugHistoriaRoute: typeof CasamentoSlugHistoriaRoute
  CasamentoSlugPadrinhosRoute: typeof CasamentoSlugPadrinhosRoute
  CasamentoSlugPresentesRoute: typeof CasamentoSlugPresentesRoute
  CasamentoSlugRecadosRoute: typeof CasamentoSlugRecadosRoute
  CasamentoSlugIndexRoute: typeof CasamentoSlugIndexRoute
  CasamentoSlugPresenteGiftIdRoute: typeof CasamentoSlugPresenteGiftIdRoute
}

const CasamentoSlugRouteChildren: CasamentoSlugRouteChildren = {
  CasamentoSlugAvisosRoute: CasamentoSlugAvisosRoute,
  CasamentoSlugConfirmarRoute: CasamentoSlugConfirmarRoute,
  CasamentoSlugFestaRoute: CasamentoSlugFestaRoute,
  CasamentoSlugFornecedoresRoute: CasamentoSlugFornecedoresRoute,
  CasamentoSlugGaleriaRoute: CasamentoSlugGaleriaRoute,
  CasamentoSlugHistoriaRoute: CasamentoSlugHistoriaRoute,
  CasamentoSlugPadrinhosRoute: CasamentoSlugPadrinhosRoute,
  CasamentoSlugPresentesRoute: CasamentoSlugPresentesRoute,
  CasamentoSlugRecadosRoute: CasamentoSlugRecadosRoute,
  CasamentoSlugIndexRoute: CasamentoSlugIndexRoute,
  CasamentoSlugPresenteGiftIdRoute: CasamentoSlugPresenteGiftIdRoute,
}

const CasamentoSlugRouteWithChildren = CasamentoSlugRoute._addFileChildren(
  CasamentoSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CasamentoSlugRoute: CasamentoSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
